# Workflow for generating (arm/bicep/etc) templates for each alert
name: Generate Templates

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - 'services/**/alerts.yaml'
      - 'tooling/generate-templates/**'

jobs:
  generate-templates:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current pr branch
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
        working-directory: tooling

      - name: Generate Templates
        run: |
          pip install -r requirements.txt
          python generate-templates.py --path ../../services --output ../../services
        working-directory: tooling/generate-templates

      - uses: rindeal/action-git-config-user@v1

      - name: Commit changes to current branch
        run: |
          echo "Committing changes to the current branch: ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          git add --force services
          git commit -m "Generate templates for alerts"
          # Push changes to the PR branch
          git push origin ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}





