# Workflow for generating (arm/bicep/etc) templates for each alert
name: Generate Templates

on:
  pull_request:
    branches:
      - main
    paths:
      - 'services/**/alerts.yaml'
      - 'tooling/generate-templates/**'

jobs:
  generate-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
        working-directory: tooling

      - name: Generate Templates
        run: |
          pip install -r requirements.txt
          python generate-templates.py --path ../../services --output ../../services
        working-directory: tooling/generate-templates

      - uses: rindeal/action-git-config-user@v1

      - name: Commit changes to current branch
        run: |
          git add --force --quiet services
          git commit -m "Generate templates for alerts"
          git push




